# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  app.countarticle:
    class: AppBundle\Services\CountArticle
    arguments: ["@doctrine.orm.entity_manager"]

  app.Commentaire:
    class: AppBundle\Twig\Commentaire
    arguments: ['@doctrine.orm.entity_manager']
    tags:
      - { name: twig.extension }
